# Generated by Django 5.1.6 on 2025-05-12 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('NUEVO', 'Nuevo Servicio'), ('VOLTAJE', 'Cambio de Voltaje'), ('LUGAR', 'Cambio de Lugar')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogCambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_afectado', models.CharField(max_length=50)),
                ('accion', models.CharField(max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParteDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParteDiario.municipio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnergiaRecuperada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_mwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('real_mwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParteDiario.partediario')),
            ],
        ),
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recibidas', models.PositiveIntegerField(default=0)),
                ('resueltas', models.PositiveIntegerField(default=0)),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParteDiario.partediario')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendientes', models.PositiveIntegerField(default=0)),
                ('ejecutados_dia', models.PositiveIntegerField(default=0)),
                ('ejecutados_mes', models.PositiveIntegerField(default=0)),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParteDiario.partediario')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParteDiario.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='PendientesPorEdad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango_edad', models.CharField(choices=[('Más de 10 días', 'Más de 10 días'), ('De 11 a 30 días', 'De 11 a 30 días'), ('De 31 a 90 días', 'De 31 a 90 días'), ('De 91 a 180 días', 'De 91 a 180 días'), ('Más de 180 días', 'Más de 180 días'), ('Más de 1 año', 'Más de 1 año')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParteDiario.registroservicio')),
            ],
        ),
    ]
