# Generated by Django 5.1.6 on 2025-05-16 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParteDiario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='logcambios',
            name='accion',
            field=models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pendientesporedad',
            name='rango_edad',
            field=models.CharField(choices=[('>10', 'Más de 10 días'), ('11-30', 'De 11 a 30 días'), ('31-90', 'De 31 a 90 días'), ('91-180', 'De 91 a 180 días'), ('>180', 'Más de 180 días'), ('>1año', 'Más de 1 año')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(choices=[('NUEVO', 'Nuevo Servicio'), ('VOLTAJE', 'Cambio de Voltaje'), ('LUGAR', 'Cambio de Lugar'), ('ENERGIA', 'Energía Recuperada'), ('QUEJAS', 'Gestión de Quejas'), ('FRAUDES', 'Fraudes Detectados'), ('CORTES', 'Cortes Ejecutados'), ('MOROSIDAD', 'Gestión de Morosidad'), ('MEDIDORES', 'Medidores Defectuosos'), ('TENDEDERAS', 'Corte a Tendederas')], max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ParteDiario.provincia'),
        ),
    ]
