# Generated by Django 5.1.6 on 2025-05-20 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParteDiario', '0002_provincia_alter_logcambios_accion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroservicio',
            name='parte',
        ),
        migrations.RemoveField(
            model_name='registroservicio',
            name='servicio',
        ),
        migrations.CreateModel(
            name='ServicioRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('NUEVO', 'Nuevo Servicio'), ('VOLTAJE', 'Cambio de Voltaje'), ('LUGAR', 'Cambio de Lugar'), ('ENERGIA', 'Energía Recuperada'), ('QUEJAS', 'Gestión de Quejas'), ('FRAUDES', 'Fraudes Detectados'), ('CORTES', 'Cortes Ejecutados'), ('MOROSIDAD', 'Gestión de Morosidad'), ('MEDIDORES', 'Medidores Defectuosos'), ('TENDEDERAS', 'Corte a Tendederas')], max_length=20, verbose_name='Tipo de Servicio')),
                ('pendientes', models.PositiveIntegerField(default=0, help_text='Casos pendientes al inicio del día', verbose_name='Pendientes')),
                ('ejecutados_dia', models.PositiveIntegerField(default=0, help_text='Casos resueltos en el día', verbose_name='Ejecutados hoy')),
                ('ejecutados_mes', models.PositiveIntegerField(default=0, help_text='Acumulado mensual', verbose_name='Ejecutados mes')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='ParteDiario.partediario')),
            ],
            options={
                'verbose_name': 'Registro de Servicio',
                'verbose_name_plural': 'Registros de Servicios',
                'ordering': ['-fecha_registro', 'tipo_servicio'],
                'unique_together': {('parte', 'tipo_servicio')},
            },
        ),
        migrations.DeleteModel(
            name='PendientesPorEdad',
        ),
        migrations.DeleteModel(
            name='RegistroServicio',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
