# Generated by Django 5.1.6 on 2025-05-27 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParteDiario', '0004_alter_partediario_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partediario',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='partediario',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='ContactoAdministrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_consulta', models.CharField(choices=[('ERROR', 'Reportar un error'), ('SUGERENCIA', 'Hacer una sugerencia'), ('CONSULTA', 'Realizar una consulta'), ('OTRO', 'Otro asunto')], default='CONSULTA', max_length=20, verbose_name='Tipo de consulta')),
                ('asunto', models.CharField(max_length=100, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje detallado')),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='contacto/adjuntos/', verbose_name='Adjuntar archivo (opcional)')),
                ('respondido', models.BooleanField(default=False, verbose_name='¿Respondido?')),
                ('notas_admin', models.TextField(blank=True, null=True, verbose_name='Notas del administrador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contacto con Administrador',
                'verbose_name_plural': 'Contactos con Administradores',
                'ordering': ['-fecha', 'respondido'],
            },
        ),
    ]
