# Generated by Django 5.1.6 on 2025-06-05 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParteDiario', '0005_alter_partediario_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientesMorosos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cliente', models.CharField(help_text='Número de identificación del cliente en el sistema', max_length=20, verbose_name='Código de cliente')),
                ('nombre_cliente', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección del servicio')),
                ('deuda_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto total adeudado (CUP)')),
                ('meses_morosidad', models.PositiveIntegerField(verbose_name='Meses de morosidad')),
                ('fecha_ultimo_pago', models.DateField(blank=True, null=True, verbose_name='Fecha del último pago realizado')),
                ('estado_gestion', models.CharField(choices=[('PENDIENTE', 'Pendiente de gestión'), ('CONTACTADO', 'Cliente contactado'), ('ACUERDO', 'Acuerdo de pago establecido'), ('PAGADO', 'Deuda saldada'), ('CORTADO', 'Servicio cortado'), ('RECONECTADO', 'Servicio reconectado')], default='PENDIENTE', max_length=20, verbose_name='Estado de gestión')),
                ('acciones_realizadas', models.TextField(blank=True, help_text='Detalle de las gestiones realizadas con el cliente', null=True, verbose_name='Acciones realizadas')),
                ('fecha_proximo_contacto', models.DateField(blank=True, null=True, verbose_name='Fecha próxima gestión')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ParteDiario.municipio', verbose_name='Municipio del cliente')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_morosos', to='ParteDiario.partediario', verbose_name='Parte diario asociado')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró')),
            ],
            options={
                'verbose_name': 'Cliente Moroso',
                'verbose_name_plural': 'Clientes Morosos',
                'ordering': ['-fecha_registro', 'municipio'],
                'unique_together': {('parte', 'codigo_cliente')},
            },
        ),
    ]
