# Generated by Django 5.1.6 on 2025-06-05 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParteDiario', '0006_clientesmorosos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OficinaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('provincia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMorosidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.CharField(max_length=20)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('deuda_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('meses_morosidad', models.PositiveIntegerField()),
                ('fecha_ultimo_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('GESTIONADO', 'Gestionado'), ('ACUERDO_PAGO', 'Acuerdo de pago'), ('PAGADO', 'Pagado'), ('CORTADO', 'Servicio cortado')], default='PENDIENTE', max_length=15)),
                ('acciones_realizadas', models.TextField(blank=True, null=True)),
                ('fecha_proximo_contacto', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morosidad', to='ParteDiario.oficinacomercial')),
            ],
            options={
                'verbose_name': 'Historial de Morosidad',
                'verbose_name_plural': 'Historiales de Morosidad',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='RegistroRecaudacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.PositiveIntegerField()),
                ('mes', models.CharField(choices=[('ENERO', 'Enero'), ('FEBRERO', 'Febrero'), ('MARZO', 'Marzo'), ('ABRIL', 'Abril'), ('MAYO', 'Mayo'), ('JUNIO', 'Junio'), ('JULIO', 'Julio'), ('AGOSTO', 'Agosto'), ('SEPTIEMBRE', 'Septiembre'), ('OCTUBRE', 'Octubre'), ('NOVIEMBRE', 'Noviembre'), ('DICIEMBRE', 'Diciembre')], max_length=15)),
                ('deuda_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deuda_cobrada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('plan_cortes_diario', models.PositiveIntegerField(default=0)),
                ('clientes_cortados_dia', models.PositiveIntegerField(default=0)),
                ('cortes_acumulados_mes', models.PositiveIntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recaudaciones', to='ParteDiario.oficinacomercial')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Recaudación',
                'verbose_name_plural': 'Registros de Recaudación',
                'ordering': ['año', 'mes', 'oficina'],
                'unique_together': {('oficina', 'año', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='ResumenAnualRecaudacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.PositiveIntegerField()),
                ('deuda_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cobrado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deuda_2021', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deuda_2022', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deuda_2023', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes_anuales', to='ParteDiario.oficinacomercial')),
            ],
            options={
                'verbose_name': 'Resumen Anual de Recaudación',
                'verbose_name_plural': 'Resúmenes Anuales de Recaudación',
                'ordering': ['-año', 'oficina'],
                'unique_together': {('oficina', 'año')},
            },
        ),
    ]
