# Generated by Django 5.1.6 on 2025-06-05 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParteDiario', '0007_oficinacomercial_historialmorosidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficinacomercial',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ParteDiario.municipio'),
        ),
        migrations.AlterField(
            model_name='oficinacomercial',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ParteDiario.provincia'),
        ),
    ]
