# Generated by Django 5.1.6 on 2025-06-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParteDiario', '0008_oficinacomercial_municipio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoadministrador',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='static/adjuntos/', verbose_name='Adjuntar archivo (opcional)'),
        ),
    ]
