# Generated by Django 5.1.6 on 2025-06-16 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParteDiario', '0009_alter_contactoadministrador_adjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='partediario',
            name='oficina_comercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ParteDiario.oficinacomercial'),
        ),
        migrations.AddField(
            model_name='partediario',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ParteDiario.provincia'),
        ),
    ]
