# Generated by Django 5.1.6 on 2025-06-16 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParteDiario', '0010_partediario_oficina_comercial_partediario_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partediario',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ParteDiario.municipio'),
        ),
    ]
