# Generated by Django 5.1.6 on 2025-06-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParteDiario', '0012_notificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partediario',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterUniqueTogether(
            name='partediario',
            unique_together={('fecha', 'oficina_comercial')},
        ),
    ]
